INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (0, 'Perwaize', 'Ahmed', 'perwaize@cis498.com', '382d65224bda884212c3f86b8b85291cdbe653b9'); -- cis498
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (0, 'Matt', 'Granum', 'matt@cis498.com', '382d65224bda884212c3f86b8b85291cdbe653b9');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (0, 'Scott', 'Langnas', 'scott@cis498.com', '382d65224bda884212c3f86b8b85291cdbe653b9');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (0, 'Mike', 'Molenda', 'mike@cis498.com', '382d65224bda884212c3f86b8b85291cdbe653b9');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Krystin', 'Lawler', 'aendn@nhictene.com', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Gina', 'Borum', 'ccelnal@uarbego.edu', '6367c48dd193d56ea7b0baad25b19455e529f5ee'); -- abc123
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Ruthie', 'Cudd', 'hsey@pila.com', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Holly', 'Ewart', 'aciynsa@oaha.org', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Antony', 'Roza', 'imwswhe@trlfoe.com', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Rosetta', 'Beatty', 'nmwhto@arjpnfbn.com', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Odessa', 'Bow', 'naduiih@tisplchd.com', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Tracy', 'Mccready', 'hnects@miin.net', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Ressie', 'Burritt', 'olf7@rrrihtt.com', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Shandi', 'Eggen', 'ctswfsai@sobfr.com', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Lezlie', 'Rolle', 'hsrvde@icfmbpy.edu', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Donnie', 'Bendixen', 'cstibenp@osstb.org', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Nisha', 'Tilman', 'uoioessr@cronreu.net', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Roxanna', 'Lossing', 'rtfeu@sufuy.org', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Edna', 'Cadle', 'eefene@ddaa.gov', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Lorina', 'Deshazo', 'toaett@asbt.edu', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Maurine', 'Almada', 'lonnee@oioiut.net', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Pete', 'Catlett', 'gds1tv@riuq.edu', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Deidre', 'Bias', 'itel@vtnln.com', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Lakia', 'Ostrow', 'zrulsna@sheihruo.org', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Jerica', 'Orosz', 'otktpeo@efeo.mil', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Ezra', 'Blakey', 'satesp@ferua.com', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Heidy', 'Hauger', 'mfpjclrn@eitoetr.net', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Lorriane', 'Leek', 'neyhion@neorpiga.org', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Renay', 'Hendricks', 'fous@ctoia.org', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Franchesca', 'Kulig', 'ysowpm@lsnc.com', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Ester', 'Moises', 'deetttws@aador.com', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Katrina', 'Crawshaw', 'ooeoafbr@cblpnt.com', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Gita', 'Stansell', 'oeieifct@mtoerrcy.com', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Daina', 'Knick', 'sasebao@goss.edu', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Rosena', 'Bolyard', 'ecem@oerheei.edu', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Vi', 'Fredericks', 'acri@tent.org', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Crystle', 'Reagle', 'feiwv@iuksw.mil', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Willis', 'Damron', 'lnoeth@oeeecyod.edu', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Shena', 'Krom', 'ioieewok@rkneaa.net', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Luigi', 'Picklesimer', 'nhoatsto@taoeuaed.mil', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Rocky', 'Hendrixson', 'rhobaik@oeot.gov', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Joelle', 'Hellickson', 'aoesrr@ureaaeua.edu', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Tama', 'Kan', 'sfedeeh@eadc.edu', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Venita', 'Isakson', 'fftenc@uoenbht.net', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Collin', 'Mowbray', 'mfooe@lsmwr.net', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Magen', 'Oathout', 'tswlec@omgru.org', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Randolph', 'Grider', 'oistelfh@aaceh.net', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Bruno', 'Aubert', 'asifsne@imotane.org', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Simona', 'Zachery', 'elortrt@tamaisit.com', '6367c48dd193d56ea7b0baad25b19455e529f5ee');
INSERT INTO `guestbookdb`.`user`(`user_type_id`, `first_name`, `last_name`, `email`, `password`) VALUES (1, 'Van', 'Biggs', 'netsongh@wiyl.org', '6367c48dd193d56ea7b0baad25b19455e529f5ee');


INSERT INTO `guestbookdb`.`event`(`event_name`, `start_date_time`, `end_date_time`, `presenter_id`, `open_registration`, `registration_code`, `mandatory_survey`, `capacity`) VALUES ('Building Webpages', '2017-07-10 10:00:00', '2017-07-10 11:00:00', 1, TRUE, 'WEBD1001', TRUE, 15);
INSERT INTO `guestbookdb`.`event`(`event_name`, `start_date_time`, `end_date_time`, `presenter_id`, `open_registration`, `registration_code`, `mandatory_survey`, `capacity`) VALUES ('Web App Hosting', '2017-07-10 10:00:00', '2017-07-10 11:00:00', 2, TRUE, 'WEBD1022', FALSE, 30);
INSERT INTO `guestbookdb`.`event`(`event_name`, `start_date_time`, `end_date_time`, `presenter_id`, `open_registration`, `registration_code`, `mandatory_survey`, `capacity`) VALUES ('MySQL Databases', '2017-07-10 13:00:00', '2017-07-10 14:00:00', 3, FALSE, 'DATA3303', FALSE, 35);
INSERT INTO `guestbookdb`.`event`(`event_name`, `start_date_time`, `end_date_time`, `presenter_id`, `open_registration`, `registration_code`, `mandatory_survey`, `capacity`) VALUES ('Coding in Java', '2017-07-10 13:00:00', '2017-07-10 14:00:00', 4, FALSE, 'PRGM1144', FALSE, 20);
INSERT INTO `guestbookdb`.`event`(`event_name`, `start_date_time`, `end_date_time`, `presenter_id`, `open_registration`, `registration_code`, `mandatory_survey`, `capacity`) VALUES ('Ancient History', '2015-01-01 10:00:00', '2015-01-01 11:00:00', 4, TRUE, 'HIST1005', TRUE, 10);
INSERT INTO `guestbookdb`.`event`(`event_name`, `start_date_time`, `end_date_time`, `presenter_id`, `open_registration`, `registration_code`, `mandatory_survey`, `capacity`) VALUES ('Interface Design', '2017-07-11 09:00:00', '2017-07-11 10:00:00', 1, TRUE, 'WEBD6006', FALSE, 20);
INSERT INTO `guestbookdb`.`event`(`event_name`, `start_date_time`, `end_date_time`, `presenter_id`, `open_registration`, `registration_code`, `mandatory_survey`, `capacity`) VALUES ('Project Planning', '2017-07-11 09:30:00', '2017-07-11 10:30:00', 2, FALSE, 'MGMT1007', TRUE, 50);
INSERT INTO `guestbookdb`.`event`(`event_name`, `start_date_time`, `end_date_time`, `presenter_id`, `open_registration`, `registration_code`, `mandatory_survey`, `capacity`) VALUES ('Handling Big Data', '2017-04-09 13:30:00', '2017-04-09:15:30', 3, TRUE, 'DATA3388', TRUE, 45);
INSERT INTO `guestbookdb`.`event`(`event_name`, `start_date_time`, `end_date_time`, `presenter_id`, `open_registration`, `registration_code`, `mandatory_survey`, `capacity`) VALUES ('Ethical Hacking', '2017-04-09 10:30:00', '2017-04-09 12:00:00', 4, TRUE, 'SECT9909', FALSE, 20);
INSERT INTO `guestbookdb`.`event`(`event_name`, `start_date_time`, `end_date_time`, `presenter_id`, `open_registration`, `registration_code`, `mandatory_survey`, `capacity`) VALUES ('Cloud Computing', '2017-04-12 14:00:00', '2017-04-12 15:00:00', 1, FALSE, 'NETW1010', FALSE, 40);
INSERT INTO `guestbookdb`.`event`(`event_name`, `start_date_time`, `end_date_time`, `presenter_id`, `open_registration`, `registration_code`, `mandatory_survey`, `capacity`) VALUES ('Network Security', '2017-04-13 09:30:00', '2017-04-13 11:00:00', 2, TRUE, 'SECT1111', TRUE, 45);
INSERT INTO `guestbookdb`.`event`(`event_name`, `start_date_time`, `end_date_time`, `presenter_id`, `open_registration`, `registration_code`, `mandatory_survey`, `capacity`) VALUES ('Building a Robot', '2017-04-13 11:30:00', '2017-04-13 15:30:00', 3, FALSE, 'PRGM1212', TRUE, 25);


INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (1, 13, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (1, 18, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (1, 19, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (1, 23, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (1, 29, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (1, 35, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (1, 36, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (1, 37, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (1, 42, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (1, 44, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 5, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 6, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 10, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 12, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 13, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 14, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 16, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 18, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 20, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 24, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 25, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 27, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 29, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 32, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 33, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 34, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 35, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 37, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 39, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 40, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 41, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (2, 44, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (3, 16, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (3, 17, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (3, 20, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (3, 21, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (3, 25, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (3, 27, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (3, 30, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (3, 33, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (3, 35, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (3, 49, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (4, 11, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (4, 13, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (4, 17, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (4, 36, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (4, 37, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (4, 41, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (4, 47, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (4, 48, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (5, 5, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (5, 9, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (5, 12, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (5, 41, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (6, 5, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (6, 12, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (6, 22, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (6, 33, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (6, 35, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (6, 44, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (6, 46, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 5, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 6, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 7, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 8, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 11, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 13, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 15, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 21, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 23, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 24, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 26, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 28, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 29, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 31, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 33, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 35, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 38, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 41, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 43, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 44, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 46, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (7, 48, 0);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 7, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 11, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 12, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 16, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 17, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 18, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 19, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 20, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 24, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 25, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 26, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 27, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 28, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 29, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 30, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 31, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 33, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 35, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 36, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 38, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 42, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 43, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (8, 49, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 8, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 9, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 10, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 14, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 18, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 19, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 20, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 22, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 23, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 24, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 25, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 26, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 28, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 30, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 31, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 32, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 33, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 38, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 39, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 40, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 41, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 44, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 45, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 47, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 48, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (9, 49, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 5, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 6, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 7, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 8, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 9, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 12, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 13, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 14, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 15, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 16, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 17, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 18, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 19, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 20, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 21, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 22, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 23, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 24, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 25, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 29, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 30, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 33, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 35, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 37, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 38, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 40, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 41, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 44, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 45, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 46, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 47, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 48, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 49, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (10, 50, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 9, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 10, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 11, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 12, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 13, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 15, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 17, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 18, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 19, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 22, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 23, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 27, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 31, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 33, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 36, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 38, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 40, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 41, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 42, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 44, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (11, 48, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (12, 5, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (12, 7, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (12, 8, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (12, 13, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (12, 16, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (12, 18, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (12, 24, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (12, 28, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (12, 32, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (12, 39, 1);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (12, 40, 2);
INSERT INTO `guestbookdb`.`event_attendance`(`event_id`, `user_id`, `attendance_status_id`) VALUES (12, 41, 2);



INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (12, 5, '2015-01-02 17:21:04', 4, 3, 4, 3, 10, 10, 2, 7, 9, 10);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (25, 5, '2015-01-02 12:38:01', 5, 10, 6, 4, 1, 5, 1, 9, 5, 7);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (9, 5, '2015-01-21 20:01:08', 8, 2, 5, 7, 10, 10, 3, 9, 9, 8);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (19, 8, '2017-04-12 11:45:11', 7, 9, 9, 1, 7, 1, 2, 5, 8, 10);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (12, 8, '2017-04-11 13:33:06', 3, 4, 3, 6, 6, 6, 5, 2, 2, 3);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (26, 8, '2017-04-10 18:23:23', 7, 10, 4, 6, 7, 10, 3, 8, 4, 7);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (43, 8, '2017-04-10 20:20:28', 6, 2, 1, 4, 2, 7, 9, 1, 2, 5);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (31, 8, '2017-04-19 09:53:17', 10, 7, 10, 9, 6, 8, 7, 9, 7, 2);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (49, 8, '2017-04-13 14:56:01', 1, 5, 2, 7, 8, 3, 6, 5, 7, 6);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (36, 8, '2017-04-11 09:00:18', 2, 7, 10, 2, 4, 5, 9, 3, 4, 2);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (28, 9, '2017-04-12 11:55:01', 6, 2, 1, 8, 9, 1, 2, 2, 2, 7);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (39, 9, '2017-04-11 13:09:09', 4, 7, 3, 8, 10, 7, 3, 2, 2, 4);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (11, 9, '2017-04-12 14:28:16', 2, 10, 9, 7, 7, 2, 10, 6, 2, 7);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (14, 9, '2017-04-10 11:16:08', 4, 3, 3, 8, 5, 10, 9, 8, 10, 5);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (25, 9, '2017-04-09 23:59:54', 9, 7, 3, 6, 3, 9, 2, 6, 2, 9);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (44, 9, '2017-04-11 13:30:30', 5, 5, 2, 9, 10, 8, 4, 9, 7, 1);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (33, 10, '2017-04-13 12:34:17', 9, 5, 7, 2, 7, 5, 5, 4, 3, 1);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (35, 10, '2017-04-19 10:11:12', 8, 1, 9, 8, 3, 8, 6, 5, 3, 8);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (9, 10, '2017-04-15 16:32:38', 3, 10, 1, 6, 7, 8, 3, 9, 10, 4);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (22, 10, '2017-04-15 09:07:19', 7, 7, 3, 8, 10, 6, 9, 3, 6, 10);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (21, 10, '2017-04-16 11:38:00', 4, 8, 7, 7, 8, 6, 3, 6, 10, 2);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (12, 10, '2017-04-16 20:26:08', 3, 7, 4, 4, 9, 7, 8, 3, 1, 9);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (25, 10, '2017-04-16 18:35:11', 1, 3, 8, 10, 4, 10, 2, 8, 10, 8);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (46, 10, '2017-04-16 11:22:01', 1, 8, 1, 5, 3, 5, 8, 3, 10, 3);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (15, 10, '2017-04-18 10:45:09', 1, 9, 7, 3, 1, 5, 5, 5, 6, 4);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (45, 10, '2017-04-14 12:21:21', 8, 3, 3, 8, 5, 8, 3, 8, 6, 6);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (40, 10, '2017-04-14 22:01:30', 6, 3, 9, 10, 3, 10, 10, 8, 3, 7);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (7, 10, '2017-04-14 11:21:34', 5, 3, 2, 4, 2, 9, 8, 5, 10, 4);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (18, 11, '2017-04-15 21:20:02', 5, 5, 3, 7, 1, 4, 6, 4, 7, 3);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (40, 11, '2017-04-15 16:38:49', 9, 2, 9, 6, 7, 3, 9, 4, 10, 9);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (19, 11, '2017-04-16 12:45:45', 10, 5, 4, 1, 10, 5, 1, 7, 8, 3);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (48, 11, '2017-04-15 15:42:11', 6, 4, 1, 10, 5, 7, 2, 1, 5, 1);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (17, 11, '2017-04-14 11:28:59', 2, 5, 1, 9, 1, 2, 9, 1, 2, 9);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (40, 12, '2017-04-13 12:25:11', 2, 3, 4, 3, 8, 1, 9, 5, 8, 10);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (41, 12, '2017-04-14 15:28:09', 10, 10, 10, 5, 5, 8, 8, 8, 10, 1);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (13, 12, '2017-04-15 10:46:57', 3, 10, 1, 7, 6, 5, 5, 1, 8, 2);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (32, 12, '2017-04-16 16:32:40', 4, 1, 9, 10, 10, 9, 2, 2, 6, 3);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (18, 12, '2017-04-16 10:28:09', 3, 5, 3, 1, 8, 6, 4, 4, 7, 1);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (5, 12, '2017-04-15 11:32:47', 1, 6, 9, 8, 9, 5, 5, 4, 9, 6);
INSERT INTO `guestbookdb`.`survey`(`user_id`, `event_id`, `submission_date_time`, `response_01`, `response_02`, `response_03`, `response_04`, `response_05`, `response_06`, `response_07`, `response_08`, `response_09`, `response_10`) VALUES (16, 12, '2017-04-14 23:01:48', 5, 8, 5, 3, 2, 6, 9, 3, 3, 1);

